[production]
url = "https://api.tastyworks.com"
wss = "wss://streamer.tastyworks.com"

[certification]
url = "https://api.cert.tastyworks.com"
wss = "wss://streamer.cert.tastyworks.com"

[authentication]
remember_me = true
mfa = false
headers.Content-Type = 'application/json'
headers.Accept = 'application/json'


