[production]
url = "https://api.tastyworks.com"
wss = "wss://streamer.tastyworks.com"

[certification]
url = "https://api.cert.tastyworks.com"
wss = "wss://streamer.cert.tastyworks.com"

[network]
# proxy = 'http://proxy-ap.sas.junta-andalucia.es:8110'
headers.Content-Type = 'application/json'
headers.Accept = 'application/json'


